//import { readable } from 'svelte/store';
export const xditor_menubarRow1 = 
{
	logo												: true,
	logoSrc											: '',
	logoLink										:	true,
	linkUrl											: '#/',
	optionalLinkText						: 'svelte',
	altText											: 'Logo',
	id													: 'xmenur1',
	type												:	'type',
	links												:
	[
		{
			url											:	'#/',
			displayInNav						: true,
			displayInFooter					: true,
			linkText								: '✎',
			id											:	'xmenur1_0',
			gid											: 'gid',
		},
		{
			url											:	'#/',
			displayInNav						: true,
			displayInFooter					: true,
			linkText								: '✔',
			id											:	'xmenur1_1',
			gid											: 'gid',
		},
		{
			url											:	'#/',
			displayInNav						: true,
			displayInFooter					: true,
			linkText								: '⚯',
			id											:	'xmenur1_2',
			gid											: 'gid',
		},
		{
			url											:	'#/',
			displayInNav						: true,
			displayInFooter					: true,
			linkText								: 'cat',
			id											:	'xmenur1_3',
			gid											: 'gid',
		},
		{
			url											:	'#/',
			displayInNav						: true,
			displayInFooter					: true,
			linkText								: 'bkx',
			id											:	'xmenur1_4',
			gid											: 'gid',
		},
		{
			url											:	'#/',
			displayInNav						: true,
			displayInFooter					: true,
			linkText								: '_5_',
			id											:	'xmenur1_5',
			gid											: 'gid',
		},
		{
			url											:	'#/',
			displayInNav						: true,
			displayInFooter					: true,
			linkText								: 'lib',
			id											:	'xmenur1_6',
			gid											: 'gid',
		},
		{
			url											:	'#/notfound',
			displayInNav						: false,
			displayInFooter					: false,
			linkText								: '',
			id											:	'xmenur1_7',
			gid											: 'gid',
		},
	],
}

export const xditor_menubarRow2 = 
{
	logo												: true,
	logoSrc											: '',
	logoLink										:	true,
	linkUrl											: '#/',
	optionalLinkText						: 'svelte',
	altText											: 'Logo',
	id													: 'xmenur2',
	type												:	'type',
	links												:
	[
		{
			url											:	'#/',
			displayInNav						: true,
			displayInFooter					: true,
			linkText								: '.',
			id											:	'xmenur2_0',
			gid											: 'gid',
		},
		{
			url											:	'#/',
			displayInNav						: true,
			displayInFooter					: true,
			linkText								: 'xx',
			id											:	'xmenur2_1',
			gid											: 'gid',
		},
		{
			url											:	'#/',
			displayInNav						: true,
			displayInFooter					: true,
			linkText								: 'th',
			id											:	'xmenur2_2',
			gid											: 'gid',
		},
		{
			url											:	'#/',
			displayInNav						: true,
			displayInFooter					: true,
			linkText								: 'en',
			id											:	'xmenur2_3',
			gid											: 'gid',
		},
		{
			url											:	'#/',
			displayInNav						: true,
			displayInFooter					: true,
			linkText								: 'ch',
			id											:	'xmenur2_4',
			gid											: 'gid',
		},
		{
			url											:	'#/',
			displayInNav						: true,
			displayInFooter					: true,
			linkText								: '✎',
			id											:	'xmenur2_5',
			gid											: 'gid',
		},
		{
			url											:	'#/',
			displayInNav						: true,
			displayInFooter					: true,
			linkText								: '⚯',
			id											:	'xmenur2_6',
			gid											: 'gid',
		},
		{
			url											:	'#/notfound',
			displayInNav						: false,
			displayInFooter					: false,
			linkText								: '',
			id											:	'xmenur2_7',
			gid											: 'gid',
		},
	],
}

export const xditor_menubarRow3 = 
{
	logo												: true,
	logoSrc											: '',
	logoLink										:	true,
	linkUrl											: '#/',
	optionalLinkText						: 'svelte',
	altText											: 'Logo',
	id													: 'xmenur3',
	type												:	'type',
	links												:
	[
		{
			url											:	'#/',
			displayInNav						: true,
			displayInFooter					: true,
			linkText								: '..',
			id											:	'xmenur3_0',
			gid											: 'gid',
		},
		{
			url											:	'#/',
			displayInNav						: true,
			displayInFooter					: true,
			linkText								: 'xx',
			id											:	'xmenur3_1',
			gid											: 'gid',
		},
		{
			url											:	'#/',
			displayInNav						: true,
			displayInFooter					: true,
			linkText								: 'th',
			id											:	'xmenur3_2',
			gid											: 'gid',
		},
		{
			url											:	'#/',
			displayInNav						: true,
			displayInFooter					: true,
			linkText								: 'en',
			id											:	'xmenur3_3',
			gid											: 'gid',
		},
		{
			url											:	'#/',
			displayInNav						: true,
			displayInFooter					: true,
			linkText								: 'ch',
			id											:	'xmenur3_4',
			gid											: 'gid',
		},
		{
			url											:	'#/',
			displayInNav						: true,
			displayInFooter					: true,
			linkText								: '✎',
			id											:	'xmenur3_5',
			gid											: 'gid',
		},
		{
			url											:	'#/',
			displayInNav						: true,
			displayInFooter					: true,
			linkText								: '❐',
			id											:	'xmenur3_6',
			gid											: 'gid',
		},
		{
			url											:	'#/notfound',
			displayInNav						: false,
			displayInFooter					: false,
			linkText								: '',
			id											:	'xmenur3_7',
			gid											: 'gid',
		},
	],
}