//import { readable } from 'svelte/store';
export const editor_menubarRow1 = 
{
	logo												: true,
	logoSrc											: '',
	logoLink										:	true,
	linkUrl											: '#/',
	optionalLinkText						: 'svelte',
	altText											: 'Logo',
	id													: 'emenur1',
	type												:	'menu',
	links												:
	[
		{
			url											:	'#/',
			displayInNav						: true,
			displayInFooter					: true,
			linkText								: 'uni',
			id											:	'emenur1_0',
			gid											: 'x',
		},
		{
			url											:	'#/',
			displayInNav						: true,
			displayInFooter					: true,
			linkText								: 'th',
			id											:	'emenur1_1',
			gid											: 'x',
		},
		{
			url											:	'#/',
			displayInNav						: true,
			displayInFooter					: true,
			linkText								: 'en',
			id											:	'emenur1_2',
			gid											: 'x',
		},
		{
			url											:	'#/',
			displayInNav						: true,
			displayInFooter					: true,
			linkText								: 'ch',
			id											:	'emenur1_3',
			gid											: 'x',
		},
		{
			url											:	'#/',
			displayInNav						: true,
			displayInFooter					: true,
			linkText								: 'all',
			id											:	'emenur1_4',
			gid											: 'x',
		},
		{
			url											:	'#/',
			displayInNav						: true,
			displayInFooter					: true,
			linkText								: '✎',
			id											:	'emenur1_5',
			gid											: 'x',
		},
		{
			url											:	'#/',
			displayInNav						: true,
			displayInFooter					: true,
			linkText								: '_6_',
			id											:	'emenur1_6',
			gid											: 'x',
		},
		{
			url											:	'#/notfound',
			displayInNav						: false,
			displayInFooter					: false,
			linkText								: '_#_',
			id											:	'emenur1_7',
			gid											: 'x',
		},
	],
}
export const editor_menubarRow2 = 
{
	logo												: true,
	logoSrc											: '',
	logoLink										:	true,
	linkUrl											: '#/',
	optionalLinkText						: 'svelte',
	altText											: 'Logo',
	id													: 'emenur2',
	type												:	'menu',
	links												:
	[
		{
			url											:	'#/',
			displayInNav						: true,
			displayInFooter					: true,
			linkText								: '{+}',
			id											:	'emenur2_0',
			gid											: 'new_tag',
		},
		{
			url											:	'#/',
			displayInNav						: true,
			displayInFooter					: true,
			linkText								: 'hx',
			id											:	'emenur2_1',
			gid											: 'new_tag',
		},
		{
			url											:	'#/',
			displayInNav						: true,
			displayInFooter					: true,
			linkText								: 'tt',
			id											:	'emenur2_2',
			gid											: 'new_tag',
		},
		{
			url											:	'#/',
			displayInNav						: true,
			displayInFooter					: true,
			linkText								: 'pr',
			id											:	'emenur2_3',
			gid											: 'new_tag',
		},
		{
			url											:	'#/',
			displayInNav						: true,
			displayInFooter					: true,
			linkText								: 'cd',
			id											:	'emenur2_4',
			gid											: 'new_tag',
		},
		{
			url											:	'#/',
			displayInNav						: true,
			displayInFooter					: true,
			linkText								: 'dm',
			id											:	'emenur2_5',
			gid											: 'new_tag',
		},
		{
			url											:	'#/',
			displayInNav						: true,
			displayInFooter					: true,
			linkText								: '☐',
			id											:	'emenur2_6',
			gid											: 'x',
		},
		{
			url											:	'#/notfound',
			displayInNav						: false,
			displayInFooter					: false,
			linkText								: '_#_',
			id											:	'emenur2_7',
			gid											: 'x',
		},
	],
}